// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtsk4qv_MKE0ht8sFjbb9cQVXbblpHs-c',
    appId: '1:168380994781:web:9bb0286e3fdd7bc47bb734',
    messagingSenderId: '168380994781',
    projectId: 'chat-app-e448a',
    authDomain: 'chat-app-e448a.firebaseapp.com',
    storageBucket: 'chat-app-e448a.appspot.com',
    measurementId: 'G-3ELLDG31TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0EaD1qxDWAm7vH_fpqduuqrRVEy8gCdg',
    appId: '1:168380994781:android:54cd4442836d7b237bb734',
    messagingSenderId: '168380994781',
    projectId: 'chat-app-e448a',
    storageBucket: 'chat-app-e448a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtVD7ygX37Z9kfhcCEb1Py_ZC3CjW-ag',
    appId: '1:168380994781:ios:6cbfde6d587bf7a47bb734',
    messagingSenderId: '168380994781',
    projectId: 'chat-app-e448a',
    storageBucket: 'chat-app-e448a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEtVD7ygX37Z9kfhcCEb1Py_ZC3CjW-ag',
    appId: '1:168380994781:ios:9d804346ef86a05a7bb734',
    messagingSenderId: '168380994781',
    projectId: 'chat-app-e448a',
    storageBucket: 'chat-app-e448a.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
